#request
int32 CUT=1
int32 SEARCH=2
int32 CHARGE=4
int32 EMPTY=3
int32 UP=5
int32 HOME=6
int32 LINEAR=7
int32 CUTBACK=8
#request type
int32 type
float64[3] transformation
---
#feedback status
int32 status
string status_string
