visual:
  tagSize: 0.07814 #default 0.10
  #camera tag graph interface trigger
  tagGraphOn: true #default false
  #camera trace result trigger
  traceResultOn: false #default true
  #camera trace debug trigger
  traceDebugOn: false #default false
  #detector color mode trigger
  colorOn: true #default false
  #detector trigger
  tagDetectorOn: false
