#all parameter should be given under the SI system
user:
 radius: 0.1 #default: 0.1
 #parameters describes the expect matrix that you want the tag ended after servo
 #expect* should be given under the camera color optical frame coordinate system
 expectX: 0.0 #default 0.0
 expectY: 0.00000 #default 0.0
 expectZ: 0.50000 #default 0.4
 #notice:only if the servoPoseOn is true, these RPY is valid
 expectRoll: 0.00000 #default 0.0
 expectPitch: 0.00000 #default 0.0
 expectYaw: 0.00000 #default 0.0
 #direction sign
 inverse: 0.0 #default false
 #trigger for pose sevo mode
 servoPoseOn: true #default false
 #debug trigger
 debugOn: 0.0
 #search down height
 searchDownHeight: -0.150000 #default -0.20
 #charge down height
 chargeDownHeight: -0.4
 #prameters temp
 goCameraX: 0.000
 goCameraY: 0.0
 goCameraZ: -0.30
 steeringDistance: 190.0
 cameraFrame: "camera_color_optical_frame"
 toolFrame: "charger_ee_link"
robot:
 #parameter constrain the robot velocity 0.0-1.0
 basicVelocity: 0.90000 #default 0.5
 #parameters constrain the robot execute precision
 goalTolerance: 0.00010 #default 0.001
 servoTolerance: 0.003 #default 0.001
 realWork: 1.0